hangman/config/routes.rb
Rails.application.routes.draw do

  resources :games
  root 'games#index'

end

hangman/app/models/game.rb
class Game < ActiveRecord::Base
  serialize :guess,Array

  def self.select_word
    words = []
    word = ""
    File.open('lib/english-dict.txt','r').each do |f|
      words << f.delete!("\n")
    end
    word = words.sample
  end

  def display_partial_word(ans,guess)
    partial_word = ""
    ans.each_char do |c|
    guess.include?(c) ? partial_word << c : partial_word << '_'
    partial_word << " "
   end
    partial_word
  end

  def is_valid?(current_guess)
    /^[a-zA-z]{1}$/ === current_guess && !self.guess.include?(current_guess)
  end

  def game_over
    self.turns.zero? || complete_word?(self.answer,self.guess)
  end

  def complete_word?(ans,guess)
    ans.chars.all? { |c| guess.include?(c) }
  end

  def turn_count(guess)
    self.turns -= 1 unless self.answer.include?(guess)
  end

end

hangman/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hangman/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @game = Game.all
  end

  def create
    word = Game.select_word
    @game = Game.create(answer: word)
    redirect_to @game
  end

  def update
    @game = Game.find(params[:id])
    guess = (params[:game][:guess]).downcase
    if @game.is_valid?(guess)
      @game.guess << guess
      @game.turn_count(guess)

      @game.save
      @game.game_over
    end
    redirect_to @game
  end

  def show
    @game = Game.find(params[:id])
    answer = @game.answer
    @guesses = @game.guess.dup
    @game.guess.clear
    @partial_word = @game.display_partial_word(answer, @guesses)
  end

end

hangman/app/helpers/application_helper.rb
module ApplicationHelper
end

hangman/app/helpers/games_helper.rb
module GamesHelper
end

hangman/app/views/games/index.html.erb
<h3>Welcome to Hangman. You know what to do!</h3>

<%= button_to "Let's Get Started", games_path %>

hangman/app/views/games/show.html.erb
<!-- show partial word for the game -->
<%=@game.answer %><br/>
<%= @partial_word %>
<br/><br/>

<!-- loop shows previous guesses -->
Letters Guessed:
<% @guesses.each do |c| %>
  <%= c %>
<% end %>
<br/><br/>

<!-- User sees how many turns are left in the game. -->
Turns Left: <%=@game.turns%>
<br/><br/>

<!-- form to intake a user's guess for the game instance -->
<%= form_for @game do |f| %>
  Guess a letter! <%= f.text_field :guess %>
<% end %>

<%=@game.game_over %>

hangman/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hangman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%=image_tag "/assets/hangman_ascii_logo.png" %>
<%= yield %>

</body>
</html>